#!/usr/bin/env Rscript

#=======================================================================
# PRIMoRDiA - Interactive Joint Residue Descriptor Density Analysis
#
# Purpose
# -------
# Read the residue-by-frame descriptor matrix generated by PRIMoRDiA,
# let the user interactively choose:
#
#   Residue A + Descriptor A
#   Residue B + Descriptor B
#
# and then:
#   1. align both descriptors by trajectory frame;
#   2. estimate their joint 2D probability density (KDE);
#   3. locate the maximum of the continuous KDE;
#   4. identify the real trajectory frame closest to that maximum;
#   5. rank additional representative frames;
#   6. save the biplot and tables.
#
# The same residue can be selected for A and B if the user wants to
# compare two descriptors of a single residue.
#
# Dependencies: ggplot2, MASS
#=======================================================================

suppressPackageStartupMessages({
    library(ggplot2)
    library(MASS)
})

#-----------------------------------------------------------------------
# Utility functions
#-----------------------------------------------------------------------

sanitize_name <- function(x) {
    x <- gsub("[^[:alnum:]_]+", "_", x)
    x <- gsub("_+", "_", x)
    x <- gsub("^_|_$", "", x)
    x
}

choose_from_list <- function(options, prompt, labels = NULL, allow_exit = TRUE) {

    if (length(options) == 0) {
        stop("No options are available.")
    }

    if (is.null(labels)) {
        labels <- options
    }

    cat("\n")

    if (allow_exit) {
        cat("  0 - Exit\n")
    }

    for (i in seq_along(options)) {
        cat(sprintf("%3d - %s\n", i, labels[i]))
    }

    repeat {

        answer <- trimws(
            readline(
                paste0("\n", prompt, ": ")
            )
        )

        index <- suppressWarnings(as.integer(answer))

        if (allow_exit && !is.na(index) && index == 0) {
            return(NULL)
        }

        if (
            !is.na(index) &&
            index >= 1 &&
            index <= length(options)
        ) {
            return(options[index])
        }

        cat(
            "Invalid selection. Choose a number between ",
            if (allow_exit) "0" else "1",
            " and ",
            length(options),
            ".\n",
            sep = ""
        )
    }
}

ask_integer <- function(prompt, default = 10, minimum = 1) {

    repeat {

        answer <- trimws(
            readline(
                sprintf("%s [default: %d]: ", prompt, default)
            )
        )

        if (answer == "") {
            return(default)
        }

        value <- suppressWarnings(as.integer(answer))

        if (!is.na(value) && value >= minimum) {
            return(value)
        }

        cat(
            "Please enter an integer >= ",
            minimum,
            ".\n",
            sep = ""
        )
    }
}

#-----------------------------------------------------------------------
# Read PRIMoRDiA residue trajectory data
#
# Supports:
#   - a commented header beginning with '#';
#   - the legacy 16-column format in which the header contained MEP
#     although MEP was not actually printed in the data rows;
#   - a future/current format in which the header and data column counts
#     agree.
#-----------------------------------------------------------------------

read_primordia_residue_data <- function(file_name) {

    if (!file.exists(file_name)) {
        stop(
            paste(
                "Input file not found:",
                file_name
            )
        )
    }

    first_lines <- readLines(
        file_name,
        n = 20,
        warn = FALSE
    )

    first_nonempty <- first_lines[
        nzchar(trimws(first_lines))
    ][1]

    header_names <- NULL

    if (
        !is.na(first_nonempty) &&
        grepl("^\\s*#", first_nonempty)
    ) {

        header_text <- sub(
            "^\\s*#\\s*",
            "",
            first_nonempty
        )

        header_names <- strsplit(
            trimws(header_text),
            "[[:space:]]+"
        )[[1]]
    }

    data <- read.table(
        file_name,
        header = FALSE,
        comment.char = "#",
        stringsAsFactors = FALSE,
        check.names = FALSE,
        fill = TRUE
    )

    # Remove columns produced only by trailing whitespace/fill, if any.
    all_na_columns <- vapply(
        data,
        function(x) all(is.na(x)),
        logical(1)
    )

    if (any(all_na_columns)) {
        data <- data[, !all_na_columns, drop = FALSE]
    }

    # Use the PRIMoRDiA header when it agrees with the data.
    if (
        !is.null(header_names) &&
        length(header_names) == ncol(data)
    ) {

        colnames(data) <- header_names

    # Legacy PRIMoRDiA output:
    # header has "... Softness_dual MEP residue"
    # but rows contain no MEP value.
    } else if (
        !is.null(header_names) &&
        length(header_names) == ncol(data) + 1 &&
        "MEP" %in% header_names &&
        tail(header_names, 1) == "residue"
    ) {

        header_names <- header_names[
            header_names != "MEP"
        ]

        colnames(data) <- header_names

        message(
            "Legacy PRIMoRDiA header detected: ",
            "'MEP' is named in the header but absent from data rows. ",
            "MEP will be ignored."
        )

    # Fallback for the known historical 16-column format.
    } else if (ncol(data) == 16) {

        colnames(data) <- c(
            "frame",
            "EAS",
            "NAS",
            "RAS",
            "Netphilicity",
            "Softness",
            "Hardness_A",
            "Hardness_B",
            "Hardness_C",
            "Hardness_D",
            "Multiphilic",
            "Electrophilic",
            "Fukushima",
            "Electron_Density",
            "Softness_dual",
            "residue"
        )

        warning(
            "The header could not be matched reliably. ",
            "Using the historical 16-column PRIMoRDiA layout."
        )

    } else {

        stop(
            paste0(
                "Could not determine the PRIMoRDiA table layout. ",
                "Data columns: ",
                ncol(data),
                if (!is.null(header_names)) {
                    paste0(
                        "; header fields: ",
                        length(header_names)
                    )
                } else {
                    "; no commented header was detected"
                },
                "."
            )
        )
    }

    if (!("frame" %in% names(data))) {
        stop("The input table does not contain a 'frame' column.")
    }

    if (!("residue" %in% names(data))) {
        stop("The input table does not contain a 'residue' column.")
    }

    data$frame <- suppressWarnings(
        as.numeric(data$frame)
    )

    data$residue <- trimws(
        as.character(data$residue)
    )

    # Convert all non-metadata columns to numeric whenever possible.
    candidate_columns <- setdiff(
        names(data),
        c("frame", "residue")
    )

    for (column_name in candidate_columns) {
        data[[column_name]] <- suppressWarnings(
            as.numeric(data[[column_name]])
        )
    }

    invalid_rows <- (
        is.na(data$frame) |
        is.na(data$residue) |
        data$residue == ""
    )

    if (any(invalid_rows)) {
        warning(
            sum(invalid_rows),
            " row(s) with invalid frame/residue were removed."
        )

        data <- data[
            !invalid_rows,
            ,
            drop = FALSE
        ]
    }

    rownames(data) <- NULL

    data
}

#-----------------------------------------------------------------------
# Identify descriptors automatically from the table.
# Only numeric columns other than "frame" are offered to the user.
#-----------------------------------------------------------------------

get_descriptor_names <- function(residue_data) {

    metadata_columns <- c(
        "frame",
        "residue"
    )

    candidate_names <- setdiff(
        names(residue_data),
        metadata_columns
    )

    descriptor_names <- candidate_names[
        vapply(
            residue_data[
                ,
                candidate_names,
                drop = FALSE
            ],
            is.numeric,
            logical(1)
        )
    ]

    descriptor_names
}

#-----------------------------------------------------------------------
# Joint 2D density analysis
#-----------------------------------------------------------------------

analyze_joint_residue_density <- function(
    residue_data,
    residue_x,
    descriptor_x,
    residue_y,
    descriptor_y,
    output_prefix = "joint_RD",
    kde_points = 250,
    number_representative_frames = 10
) {

    if (!(descriptor_x %in% colnames(residue_data))) {
        stop(
            paste(
                "Descriptor not found:",
                descriptor_x
            )
        )
    }

    if (!(descriptor_y %in% colnames(residue_data))) {
        stop(
            paste(
                "Descriptor not found:",
                descriptor_y
            )
        )
    }

    #--------------------------------------------------------
    # Extract the two selected residue/descriptor series
    #--------------------------------------------------------

    data_x <- residue_data[
        residue_data$residue == residue_x,
        c("frame", descriptor_x),
        drop = FALSE
    ]

    data_y <- residue_data[
        residue_data$residue == residue_y,
        c("frame", descriptor_y),
        drop = FALSE
    ]

    if (nrow(data_x) == 0) {
        stop(
            paste(
                "No data found for residue:",
                residue_x
            )
        )
    }

    if (nrow(data_y) == 0) {
        stop(
            paste(
                "No data found for residue:",
                residue_y
            )
        )
    }

    colnames(data_x) <- c(
        "frame",
        "descriptor_x"
    )

    colnames(data_y) <- c(
        "frame",
        "descriptor_y"
    )

    if (anyDuplicated(data_x$frame)) {
        stop(
            paste(
                "Duplicated frames were found for residue",
                residue_x
            )
        )
    }

    if (anyDuplicated(data_y$frame)) {
        stop(
            paste(
                "Duplicated frames were found for residue",
                residue_y
            )
        )
    }

    #--------------------------------------------------------
    # Align the two time series explicitly by frame
    #--------------------------------------------------------

    missing_for_x <- setdiff(
        data_y$frame,
        data_x$frame
    )

    missing_for_y <- setdiff(
        data_x$frame,
        data_y$frame
    )

    if (length(missing_for_x) > 0) {
        warning(
            paste(
                "Frames missing for",
                residue_x,
                ":",
                paste(
                    missing_for_x,
                    collapse = ", "
                )
            )
        )
    }

    if (length(missing_for_y) > 0) {
        warning(
            paste(
                "Frames missing for",
                residue_y,
                ":",
                paste(
                    missing_for_y,
                    collapse = ", "
                )
            )
        )
    }

    joint_data <- merge(
        data_x,
        data_y,
        by = "frame",
        all = FALSE,
        sort = TRUE
    )

    finite_rows <- (
        is.finite(joint_data$descriptor_x) &
        is.finite(joint_data$descriptor_y)
    )

    if (any(!finite_rows)) {
        warning(
            sum(!finite_rows),
            " frame(s) with non-finite descriptor values were removed."
        )

        joint_data <- joint_data[
            finite_rows,
            ,
            drop = FALSE
        ]
    }

    if (nrow(joint_data) < 5) {
        stop(
            "At least five common valid frames are required."
        )
    }

    if (length(unique(joint_data$descriptor_x)) < 2) {
        stop(
            paste(
                descriptor_x,
                "has insufficient variation for 2D KDE."
            )
        )
    }

    if (length(unique(joint_data$descriptor_y)) < 2) {
        stop(
            paste(
                descriptor_y,
                "has insufficient variation for 2D KDE."
            )
        )
    }

    #========================================================
    # 2D Kernel Density Estimate
    #========================================================

    kde_result <- MASS::kde2d(
        joint_data$descriptor_x,
        joint_data$descriptor_y,
        n = kde_points
    )

    maximum_index <- arrayInd(
        which.max(kde_result$z),
        dim(kde_result$z)
    )

    density_mode_x <- kde_result$x[
        maximum_index[1]
    ]

    density_mode_y <- kde_result$y[
        maximum_index[2]
    ]

    maximum_density <- kde_result$z[
        maximum_index[1],
        maximum_index[2]
    ]

    #========================================================
    # Find real trajectory frames closest to the KDE maximum.
    #
    # Distance is standardized by the SD of each descriptor,
    # so one descriptor does not dominate only because of its
    # numerical scale.
    #========================================================

    scale_x <- sd(
        joint_data$descriptor_x,
        na.rm = TRUE
    )

    scale_y <- sd(
        joint_data$descriptor_y,
        na.rm = TRUE
    )

    if (
        !is.finite(scale_x) ||
        !is.finite(scale_y) ||
        scale_x == 0 ||
        scale_y == 0
    ) {
        stop(
            "One descriptor has zero/invalid standard deviation."
        )
    }

    joint_data$distance_to_mode <- sqrt(
        (
            (
                joint_data$descriptor_x -
                density_mode_x
            ) /
            scale_x
        )^2
        +
        (
            (
                joint_data$descriptor_y -
                density_mode_y
            ) /
            scale_y
        )^2
    )

    joint_data <- joint_data[
        order(joint_data$distance_to_mode),
        ,
        drop = FALSE
    ]

    number_representative_frames <- min(
        number_representative_frames,
        nrow(joint_data)
    )

    representative_frames <- head(
        joint_data,
        number_representative_frames
    )

    # If PRIMoRDiA frames are zero-based, also provide a
    # one-based trajectory index for convenience.
    if (min(joint_data$frame, na.rm = TRUE) == 0) {

        joint_data$trajectory_index_1based <-
            joint_data$frame + 1

        representative_frames$trajectory_index_1based <-
            representative_frames$frame + 1
    }

    best_frame <- representative_frames[
        1,
        ,
        drop = FALSE
    ]

    #========================================================
    # KDE grid for plotting
    #========================================================

    kde_grid <- expand.grid(
        descriptor_x = kde_result$x,
        descriptor_y = kde_result$y
    )

    kde_grid$density <- as.vector(
        kde_result$z
    )

    mode_data <- data.frame(
        descriptor_x = density_mode_x,
        descriptor_y = density_mode_y
    )

    #========================================================
    # Plot
    #
    # Filled KDE contours reproduce the idea of the older
    # PRIMoRDiA/R analyses while avoiding a uniformly colored
    # raster over very-low-density regions.
    #========================================================

    density_plot <- ggplot() +

        geom_contour_filled(
            data = kde_grid,
            aes(
                x = descriptor_x,
                y = descriptor_y,
                z = density
            ),
            bins = 12,
            alpha = 0.85
        ) +

        geom_contour(
            data = kde_grid,
            aes(
                x = descriptor_x,
                y = descriptor_y,
                z = density
            ),
            bins = 12,
            linewidth = 0.35,
            alpha = 0.70
        ) +

        geom_point(
            data = joint_data,
            aes(
                x = descriptor_x,
                y = descriptor_y
            ),
            size = 1.3,
            alpha = 0.35
        ) +

        # Continuous KDE maximum.
        geom_point(
            data = mode_data,
            aes(
                x = descriptor_x,
                y = descriptor_y
            ),
            shape = 4,
            size = 4.5,
            stroke = 1.3
        ) +

        # Real trajectory frame closest to KDE maximum.
        geom_point(
            data = best_frame,
            aes(
                x = descriptor_x,
                y = descriptor_y
            ),
            shape = 21,
            size = 4.5,
            stroke = 1.2,
            fill = "white"
        ) +

        annotate(
            "text",
            x = best_frame$descriptor_x,
            y = best_frame$descriptor_y,
            label = paste0(
                "Frame ",
                best_frame$frame
            ),
            hjust = -0.12,
            vjust = -0.8,
            size = 3.5
        ) +

        scale_fill_viridis_d(
            option = "C",
            direction = -1,
            name = "KDE density"
        ) +

        theme_minimal(base_size = 12) +

        theme(
            legend.position = "right",
            plot.title = element_text(face = "bold")
        ) +

        labs(
            title = "Joint residue descriptor probability density",
            subtitle = paste0(
                descriptor_x,
                " (",
                residue_x,
                ")  vs  ",
                descriptor_y,
                " (",
                residue_y,
                ")"
            ),
            x = paste(
                descriptor_x,
                "-",
                residue_x
            ),
            y = paste(
                descriptor_y,
                "-",
                residue_y
            )
        )

    #========================================================
    # Save outputs
    #========================================================

    write.table(
        joint_data,
        file = paste0(
            output_prefix,
            "_joint_values.tsv"
        ),
        sep = "\t",
        quote = FALSE,
        row.names = FALSE
    )

    write.table(
        representative_frames,
        file = paste0(
            output_prefix,
            "_representative_frames.tsv"
        ),
        sep = "\t",
        quote = FALSE,
        row.names = FALSE
    )

    mode_summary <- data.frame(
        residue_A = residue_x,
        descriptor_A = descriptor_x,
        KDE_mode_A = density_mode_x,
        residue_B = residue_y,
        descriptor_B = descriptor_y,
        KDE_mode_B = density_mode_y,
        maximum_density = maximum_density,
        representative_frame = best_frame$frame,
        representative_A = best_frame$descriptor_x,
        representative_B = best_frame$descriptor_y,
        distance_to_mode = best_frame$distance_to_mode,
        common_frames = nrow(joint_data),
        stringsAsFactors = FALSE
    )

    if ("trajectory_index_1based" %in% names(best_frame)) {
        mode_summary$trajectory_index_1based <-
            best_frame$trajectory_index_1based
    }

    write.table(
        mode_summary,
        file = paste0(
            output_prefix,
            "_mode.tsv"
        ),
        sep = "\t",
        quote = FALSE,
        row.names = FALSE
    )

    ggsave(
        filename = paste0(
            output_prefix,
            "_density.png"
        ),
        plot = density_plot,
        width = 7,
        height = 5.5,
        dpi = 600
    )

    ggsave(
        filename = paste0(
            output_prefix,
            "_density.pdf"
        ),
        plot = density_plot,
        width = 7,
        height = 5.5
    )

    return(
        list(
            joint_data = joint_data,
            kde = kde_result,
            mode = mode_summary,
            representative_frames = representative_frames,
            plot = density_plot
        )
    )
}

#-----------------------------------------------------------------------
# Interactive analysis
#-----------------------------------------------------------------------

run_interactive_analysis <- function(
    residue_data,
    input_file
) {

    descriptors <- get_descriptor_names(
        residue_data
    )

    residues <- sort(
        unique(
            residue_data$residue
        )
    )

    residue_counts <- table(
        residue_data$residue
    )

    residue_labels <- paste0(
        residues,
        "  (",
        as.integer(
            residue_counts[residues]
        ),
        " frames)"
    )

    if (length(residues) == 0) {
        stop(
            "No monitored residues were found."
        )
    }

    if (length(descriptors) < 2) {
        stop(
            "Fewer than two numeric descriptors are available."
        )
    }

    cat("\n")
    cat("============================================================\n")
    cat(" PRIMoRDiA Joint Residue Descriptor Density Analysis\n")
    cat("============================================================\n")
    cat("\n")
    cat("Input file: ", input_file, "\n", sep = "")
    cat(
        "Frames detected: ",
        length(unique(residue_data$frame)),
        "\n",
        sep = ""
    )
    cat(
        "Monitored residue labels: ",
        length(residues),
        "\n",
        sep = ""
    )
    cat(
        "Available descriptors: ",
        length(descriptors),
        "\n",
        sep = ""
    )

    cat(
        "\nThis analysis estimates the joint 2D probability density\n",
        "of two residue-level descriptors along the trajectory.\n",
        "It also identifies real trajectory frames closest to the\n",
        "maximum of the estimated probability density.\n",
        sep = ""
    )

    cat(
        "\nThe same residue may be selected twice if you want to\n",
        "compare two descriptors of one residue.\n"
    )

    repeat {

        cat("\n")
        cat("------------------------------------------------------------\n")
        cat(" Select the first residue/descriptor pair (X axis)\n")
        cat("------------------------------------------------------------\n")

        residue_a <- choose_from_list(
            residues,
            "Select residue A",
            labels = residue_labels
        )

        if (is.null(residue_a)) {
            break
        }

        descriptor_a <- choose_from_list(
            descriptors,
            paste(
                "Select descriptor for",
                residue_a
            )
        )

        if (is.null(descriptor_a)) {
            break
        }

        cat("\n")
        cat("------------------------------------------------------------\n")
        cat(" Select the second residue/descriptor pair (Y axis)\n")
        cat("------------------------------------------------------------\n")

        residue_b <- choose_from_list(
            residues,
            "Select residue B",
            labels = residue_labels
        )

        if (is.null(residue_b)) {
            break
        }

        descriptor_b <- choose_from_list(
            descriptors,
            paste(
                "Select descriptor for",
                residue_b
            )
        )

        if (is.null(descriptor_b)) {
            break
        }

        number_frames <- ask_integer(
            "How many representative frames should be reported?",
            default = 10,
            minimum = 1
        )

        cat("\nSelected analysis:\n")
        cat(
            "  X: ",
            descriptor_a,
            " of ",
            residue_a,
            "\n",
            sep = ""
        )
        cat(
            "  Y: ",
            descriptor_b,
            " of ",
            residue_b,
            "\n",
            sep = ""
        )

        output_prefix <- paste0(
            sanitize_name(residue_a),
            "_",
            sanitize_name(descriptor_a),
            "__",
            sanitize_name(residue_b),
            "_",
            sanitize_name(descriptor_b)
        )

        result <- tryCatch(

            analyze_joint_residue_density(
                residue_data = residue_data,
                residue_x = residue_a,
                descriptor_x = descriptor_a,
                residue_y = residue_b,
                descriptor_y = descriptor_b,
                output_prefix = output_prefix,
                number_representative_frames = number_frames
            ),

            error = function(e) {

                cat(
                    "\nAnalysis failed:\n  ",
                    conditionMessage(e),
                    "\n",
                    sep = ""
                )

                return(NULL)
            }
        )

        if (!is.null(result)) {

            cat("\n")
            cat("============================================================\n")
            cat(" Analysis completed\n")
            cat("============================================================\n")

            cat(
                "\nKDE maximum:\n  ",
                descriptor_a,
                " (",
                residue_a,
                ") = ",
                signif(
                    result$mode$KDE_mode_A,
                    7
                ),
                "\n  ",
                descriptor_b,
                " (",
                residue_b,
                ") = ",
                signif(
                    result$mode$KDE_mode_B,
                    7
                ),
                "\n",
                sep = ""
            )

            cat(
                "\nMost representative PRIMoRDiA frame: ",
                result$mode$representative_frame,
                "\n",
                sep = ""
            )

            if (
                "trajectory_index_1based" %in%
                names(result$mode)
            ) {
                cat(
                    "Corresponding 1-based trajectory index: ",
                    result$mode$trajectory_index_1based,
                    "\n",
                    sep = ""
                )
            }

            cat(
                "Common frames used in KDE: ",
                result$mode$common_frames,
                "\n",
                sep = ""
            )

            cat("\nRepresentative-frame ranking:\n")

            print(
                result$representative_frames,
                row.names = FALSE
            )

            cat("\nFiles written:\n")
            cat(
                "  ",
                output_prefix,
                "_density.png\n",
                sep = ""
            )
            cat(
                "  ",
                output_prefix,
                "_density.pdf\n",
                sep = ""
            )
            cat(
                "  ",
                output_prefix,
                "_mode.tsv\n",
                sep = ""
            )
            cat(
                "  ",
                output_prefix,
                "_representative_frames.tsv\n",
                sep = ""
            )
            cat(
                "  ",
                output_prefix,
                "_joint_values.tsv\n",
                sep = ""
            )
        }

        answer <- tolower(
            trimws(
                readline(
                    "\nRun another joint analysis? [y/N]: "
                )
            )
        )

        if (!(answer %in% c("y", "yes", "s", "sim"))) {
            break
        }
    }

    cat("\nPRIMoRDiA R analysis finished.\n")
}

#=======================================================================
# Main
#=======================================================================

args <- commandArgs(
    trailingOnly = TRUE
)

# Default: use the standard PRIMoRDiA trajectory-residue output name.
input_file <- "residues_data_frames"

# Optional:
# Rscript primordia_joint_density_interactive.R path/to/residues_data_frames
if (length(args) >= 1) {
    input_file <- args[1]
}

if (!file.exists(input_file)) {

    cat(
        "Default/input file was not found:\n  ",
        input_file,
        "\n",
        sep = ""
    )

    user_file <- trimws(
        readline(
            "Enter the path to the PRIMoRDiA residues_data_frames file: "
        )
    )

    if (user_file == "" || !file.exists(user_file)) {
        stop(
            "A valid PRIMoRDiA residue trajectory file is required."
        )
    }

    input_file <- user_file
}

residue_data <- read_primordia_residue_data(
    input_file
)

run_interactive_analysis(
    residue_data = residue_data,
    input_file = input_file
)
